# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://madamullac.github.io
title: madAmullaC
email: your-email@domain.com
description: we are madamullac, we are legion.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/madamullac
  - title: linkedin
    url: 
